environment: default
server:
  port: 8080
welcomeMsg: "Hello from default"
---
environment: test
server:
  port: 4000
welcomeMsg: "Hello from test"
---
environment: prod
server:
  port: 5000
welcomeMsg: "Hello from prod"